/**
 * 
 */
package org.opentides.web.controller;

import org.opentides.bean.Ninja;
import org.opentides.controller.BaseCrudController;

import jorg.opentides.bean.SystemCodes;

import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;


/**
 * This is the controller class for Ninja.
 * Scaffold generated by opentides3 on Oct 28, 2014 02:08:02. 
 * @author opentides
 */
 
@RequestMapping("/ninja")
@Controller
public class NinjaCrudController extends BaseCrudController<Ninja> {

	@Autowired
	NinjaService ninjaService;
	
	/**
	 * Method to return a static list of gender.
	 * 
	 * @return list of SystemCodes
	 */
	@ModelAttribute("genderList")
	public List<String> genderList() {
		return Arrays.asList(new String[] {"Male", "Female"});
	}
	/**
	 * Method to return a list of status based on 
	 * System Codes.
	 * 
	 * @return list of SystemCodes
	 */
	@ModelAttribute("statusList")
	public List<SystemCodes> statusList() {
		return getSystemCodesByCategory("STATUS");
	}
}