/*
 * ChangeLogDaoJpaImpl.java
 */
package org.opentides.dao.impl;

import org.opentides.bean.ChangeLog;
import org.opentides.dao.ChangeLogDao;
import org.springframework.stereotype.Repository;
  

/**
 * This is the dao implementation for ChangeLog.
 * Scaffold generated by opentides3 on Oct 06, 2014 11:59:58. 
 * @author opentides
 */
@Repository("changeLogDao")
public class ChangeLogDaoJpaImpl extends BaseEntityDaoJpaImpl<ChangeLog, Long>
		implements ChangeLogDao {
	
}
