/*
 * ChangeLogDaoJpaImpl.java
 */
package org.opentides.dao.impl;

import java.util.ArrayList;

import javax.persistence.Query;

import org.opentides.bean.ChangeLog;
import org.opentides.dao.ChangeLogDao;
import org.springframework.stereotype.Repository;

/**
 * This is the dao implementation for ChangeLog. Scaffold generated by
 * opentides3 on Oct 06, 2014 11:59:58.
 * 
 * @author opentides
 */
@Repository("changeLogDao")
public class ChangeLogDaoJpaImpl extends BaseEntityDaoJpaImpl<ChangeLog, Long>
		implements ChangeLogDao {

	@Override
	public ChangeLog findLatestChangeByBranch(Long branchId) {
		String jpql = getJpqlQuery("jpql.mobilesync.findLastestChangeByBranch");
		Query query = getEntityManager().createQuery(jpql);
		query.setParameter("branchId", branchId);
		query.setMaxResults(1);

		ArrayList<ChangeLog> logs = (ArrayList<ChangeLog>) query.getResultList();
		
		if(!logs.isEmpty()){
			return (ChangeLog) query.getResultList().get(0);
		}
		
		return null;
	}

}
