/*
 * SyncEndpointDaoJpaImpl.java
 */
package org.opentides.dao.impl;

import org.opentides.bean.SyncEndpoint;
import org.opentides.dao.SyncEndpointDao;
import org.springframework.stereotype.Repository;
  

/**
 * This is the dao implementation for SyncEndpoint.
 * Scaffold generated by opentides3 on Jan 17, 2015 08:39:59. 
 * @author opentides
 */
@Repository(value="syncEndpointDao")
public class SyncEndpointDaoJpaImpl extends BaseEntityDaoJpaImpl<SyncEndpoint, Long>
		implements SyncEndpointDao {

}
