/*
 * NinjaServiceImpl.java
 */
package org.opentides.service.impl;

import org.opentides.bean.Ninja;
import org.opentides.service.NinjaService;
import org.opentides.service.impl.BaseCrudServiceImpl;

/**
 * This is the service implementation for Ninja.
 * Scaffold generated by opentides3 on Oct 26, 2014 10:59:57. 
 * @author opentides
 *
 */
 @Service(value = "ninjaService")
public class NinjaServiceImpl extends BaseCrudServiceImpl<Ninja>
		implements NinjaService {
		
}
