/*
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.    
 */
package org.opentides.service.impl;

import java.util.List;

import org.opentides.annotation.CrudSecure;
import org.opentides.bean.SystemCodes;
import org.opentides.dao.SystemCodesDao;
import org.opentides.service.SystemCodesService;
import org.springframework.stereotype.Service;

/**
 * This is the service implementation for SystemCodes.
 * Scaffold generated by opentides3 on Jan 16, 2013 12:40:25. 
 * @author opentides
 *
 */
@Service(value="systemCodesService")
@CrudSecure("SYSTEM_CODES")
public class SystemCodesServiceImpl extends BaseCrudServiceImpl<SystemCodes>
		implements SystemCodesService {
	
	public List<String> getAllCategories() {
		return getSystemCodesDao().getAllCategories();
	}

	public SystemCodes findByKey(SystemCodes systemCodes) {
		return getSystemCodesDao().loadBySystemCodesByKey(systemCodes.getKey());
	}
	
	public SystemCodes findByKey(String systemCodes) {
		return getSystemCodesDao().loadBySystemCodesByKey(systemCodes);
	}

	public List<SystemCodes> findSystemCodesByCategory(String category) {
		return getSystemCodesDao().findSystemCodesByCategory(category);
	}

	public List<String> getAllCategoriesExcept(String... categories) {
		return getSystemCodesDao().getAllCategoriesExcept(categories);
	}
	
	public SystemCodesDao getSystemCodesDao() {
		return (SystemCodesDao) super.getDao();
	}

	@Override
	public boolean isDuplicateKey(SystemCodes systemCodes) {
		if (getSystemCodesDao().countDuplicate(systemCodes) > 0)
			return true;
		else
			return false;
	}
	
	@Override
	public boolean isParentValid(SystemCodes systemCodes) {
		SystemCodes parent = systemCodes.getParent();
		if(parent != null) {
			
		}
		return true;
	}
}
