/*
 * NinjaService.java
 */
package org.opentides.service;

import org.opentides.bean.Ninja;
import org.opentides.service.BaseCrudService;

/**
 * This is the service interface for Ninja.
 * Scaffold generated by opentides3 on Oct 28, 2014 02:08:02. 
 * @author opentides
 */
 
public interface NinjaService extends BaseCrudService<Ninja> {

}
