/*
 * NinjaService.java
 */
package org.opentides.service;

import org.opentides.bean.Ninja;
import org.opentides.service.BaseCrudService;

/**
 * This is the service interface for Ninja.
 * Scaffold generated by opentides3 on Oct 26, 2014 10:59:57. 
 * @author opentides
 */
 
public interface NinjaService extends BaseCrudService<Ninja> {

}
