/*
 * SyncEndpointService.java
 */
package org.opentides.service;

import org.opentides.bean.SyncEndpoint;

/**
 * This is the service interface for SyncEndpoint.
 * Scaffold generated by opentides3 on Jan 17, 2015 08:39:59. 
 * @author opentides
 */
 
public interface SyncEndpointService extends BaseCrudService<SyncEndpoint> {
	
	public SyncEndpoint findSyncEndpointByClientCode(String clientcode);

}
