/* 
 * NinjaDao.java
 */
package org.opentides.dao;

import org.opentides.bean.Ninja;
import org.opentides.dao.BaseEntityDao;

/**
 * This is the dao interface for Ninja.
 * Scaffold generated by opentides3 on Oct 28, 2014 10:53:15. 
 * @author opentides
 */
 
public interface NinjaDao extends BaseEntityDao<Ninja, Long> {

}