/* 
 * CashCountDao.java
 */
package org.opentides.dao;

import org.opentides.bean.ChangeLog;

/**
 * This is the dao interface for ChangeLog.
 * Scaffold generated by opentides3 on Oct 06, 2014 11:59:58. 
 * @author opentides
 */
 
public interface ChangeLogDao extends BaseEntityDao<ChangeLog, Long> {

	/**
	 * Returns the latest change log filtered by id
	 * @param branchId
	 * @return
	 */
	public ChangeLog findLatestChangeByBranch(Long branchId);
	
}