/* 
 * SyncEndpointDao.java
 */
package org.opentides.dao;

import org.opentides.bean.SyncEndpoint;

/**
 * This is the dao interface for SyncEndpoint.
 * Scaffold generated by opentides3 on Jan 17, 2015 08:39:59. 
 * @author opentides
 */
 
public interface SyncEndpointDao extends BaseEntityDao<SyncEndpoint, Long> {

}